name: rels
version: '0.0.0'
version-script: git describe --always | cut -c 2-
summary: Github release analytics for the console
description: |
  By utilizing a simple and minimal usage syntax rels enables you to easily view various
  analytics and stats regarding the releases of any GitHub repository, displayed in a clean
  and concise manner, right from within your terminal.

grade: stable
confinement: strict

architectures:
  - amd64
  - i386
  - armhf

apps:
  rels:
    command: rels
    plugs:
      - home
      - network
      - network-control

parts:
  rels:
    plugin: nodejs
    node-engine: 10.15.0
    node-package-manager: yarn
    source: .
